data_dir: catkin_ws/src/data
model_dir: catkin_ws/src/models

# Inference Configuration
planner:
  gripper_width: 0.08
  height: 0.015
  num_push_directions: 4 
  visualize: False
  learning_base: True
  # image_type: 'masked_origin_image'
  image_type: 'masked_image'

depth_based:
  friction_coefficient: 1

network:
  model_name: "2024-05-16-0000"
  # model_name: "2024-05-07-0000"
  network_threshold: 0.2

hybrid:
  grid_size: 0.05  # unit: m
  dtheta:  5  # unit: deg

# Train Configuration
file_zero_padding_num: 7
base_lr: 0.0002
decay_rate: 0.95
train_l2_regularizer: 0.0005
batch_size: 64
num_epochs: 40
momentum_rate: 0.9
network_threshold: 0.01

# Anlyzation tool configuration for trained model
confusion:
  num_pushes: 1 # How many push cases you want to analyze
  num_data_points: 3000 # How many test samples you want to analyze

network_output:
  num_pushes: 4 # How many push cases you want to analyze
  num_data_points: 2000 # How many test samples you want to analyze

feature:
  num_data_points: 5000 # How many data points you want to analyze
