data_dir: catkin_ws/src/data
model_dir: catkin_ws/src/models

# Inference Configuration
planner:
  gripper_width: 0.08
  height: 0.015
  num_push_directions: 4 
  visualize: False
  learning_base: True
  # image_type: 'masked_origin _image'
  image_type: 'masked_image'

depth_based:
  friction_coefficient: 1

network:
  # model_name: "2023-10-15-2157_zivid"
  # model_name: "2024-04-23-1601"
  model_name: "2024-05-07-1153"
  # model_name: "2024-05-07-0000"
  network_threshold: 0.2

hybrid:
  grid_size: 0.05  # unit: m
  dtheta:  5  # unit: deg

# Train Configuration
file_zero_padding_num: 7
base_lr: 0.0001
# base_lr: 0.1
decay_rate: 0.95
train_l2_regularizer: 0.0005
# batch_size: 64
batch_size: 32
num_epochs: 60
momentum_rate: 0.9
# model_name: "2023-08-25-0547"
network_threshold: 0.01
StablePushNet:
  image_height: 96
  image_width: 96
  batch_size: 64

# Anlyzation tool configuration for trained model
confusion:
  num_pushes: 1 # How many push cases you want to analyze
  num_data_points: 3000 # How many test samples you want to analyze

feature:
  num_data_points: 5000 # How many data points you want to analyze

network_output:
  num_pushes: 4 # How many push cases you want to analyze
  # num_pushes: 36 # How many push cases you want to analyze
